theme: minima
title: Laura's Website
author: Laura Pei
email: lauraspberrypie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome description for my new site.  # It will appear in my document head meta (for Google search results) and in my feed.xml site description.

# social links
twitter_username: lauraspberry # DO NOT include the @ character, or else the build will fail!
github_username:  lauraspberry # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
